version: '3'

services:
  mysql:
    image: mysql:8.0.29
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/dev/mysql/startup.sql:/docker-entrypoint-initdb.d/startup.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build:
      dockerfile: ./docker/dev/app/Dockerfile
    volumes:
      - .:/application
    command: sleep 100000
    env_file:
      - .env

  migration-hook:
    build:
      dockerfile: ./docker/dev/app/Dockerfile
    volumes:
      - .:/application
    command: ./vendor/bin/doctrine-migrations migrations:migrate --configuration src/Delivery/Shared/Migration/migrations.yaml --db-configuration src/Delivery/Shared/Dbal/migrations-db.php
    env_file:
      - .env

volumes:
  mysql-volume:
