services:

  App\Delivery\Driver\Query\GetDriverHandler:
    arguments:
      $driverRepository: '@delivery.driver.repository'
  App\Delivery\Driver\Query\GetFreeDriversAroundHandler:
    arguments:
     $driverRepository: '@delivery.driver.repository'

  delivery.driver.query.bus:
    class: App\Delivery\Shared\Bus\QueryBus
    public: true
    arguments:
      $handlers:
        App\Delivery\Driver\Query\GetDriverQuery: '@App\Delivery\Driver\Query\GetDriverHandler'
        App\Delivery\Driver\Query\GetFreeDriversAroundQuery: '@App\Delivery\Driver\Query\GetFreeDriversAroundHandler'

  App\Delivery\Trip\Query\GetTripHandler:
    arguments:
     $tripRepository: '@delivery.trip.repository'

  delivery.trip.query.bus:
    class: App\Delivery\Shared\Bus\QueryBus
    public: true
    arguments:
      $handlers:
        App\Delivery\Trip\Query\GetTripQuery: '@App\Delivery\Trip\Query\GetTripHandler'

  App\Delivery\Driver\Command\MarkDriverFreeHandler:
    arguments:
      $driverQueryBus: '@delivery.driver.query.bus'
      $driverRepository: '@delivery.driver.repository'
  App\Delivery\Driver\Command\MarkDriverBusyHandler:
    arguments:
      $driverQueryBus: '@delivery.driver.query.bus'
      $driverRepository: '@delivery.driver.repository'
  App\Delivery\Driver\Command\ScoutDriverHandler:
    arguments:
      $driverRepository: '@delivery.driver.repository'
      $configurationManager: '@delivery.configuration.manager'
      $driverQueryBus: '@delivery.driver.query.bus'
      $tripQueryBus: '@delivery.trip.query.bus'
  App\Delivery\Trip\Command\CreateTripHandler:
    arguments:
      $persistingTripRepository: '@App\Delivery\Trip\PersistingTripRepository'
  App\Delivery\Trip\Command\RecruitDriverHandler:
    arguments:
      $driverRepository: '@delivery.driver.repository'
      $tripRepository: '@delivery.trip.repository'
  App\Delivery\Driver\Command\CreateDriverHandler:
    arguments:
      $driverRepository: '@delivery.driver.repository'
  App\Delivery\Driver\Command\UpdateDriverLocationHandler:
    arguments:
      $driverRepository: '@delivery.driver.repository'
  App\Delivery\Driver\Command\UnreserveDriversHandler:
    arguments:
      $driverRepository: '@delivery.driver.repository'
  App\Delivery\Trip\Command\MarkTripAsDeliveredHandler:
    arguments:
      $tripQueryBus: '@delivery.trip.query.bus'
      $tripRepository: '@delivery.trip.repository'

  delivery.driver.command.bus:
    class: App\Delivery\Shared\Bus\CommandBus
    public: true
    arguments:
      $handlers:
        App\Delivery\Driver\Command\CreateDriverCommand: '@App\Delivery\Driver\Command\CreateDriverHandler'
        App\Delivery\Driver\Command\ScoutDriverCommand: '@App\Delivery\Driver\Command\ScoutDriverHandler'
        App\Delivery\Driver\Command\MarkDriverBusyCommand: '@App\Delivery\Driver\Command\MarkDriverBusyHandler'
        App\Delivery\Driver\Command\MarkDriverFreeCommand: '@App\Delivery\Driver\Command\MarkDriverFreeHandler'
        App\Delivery\Driver\Command\UpdateDriverLocationCommand: '@App\Delivery\Driver\Command\UpdateDriverLocationHandler'
        App\Delivery\Driver\Command\UnreserveDriversCommand: '@App\Delivery\Driver\Command\UnreserveDriversHandler'

  delivery.trip.command.bus:
    class: App\Delivery\Shared\Bus\CommandBus
    public: true
    arguments:
      $handlers:
        App\Delivery\Trip\Command\CreateTripCommand: '@App\Delivery\Trip\Command\CreateTripHandler'
        App\Delivery\Trip\Command\RecruitDriverCommand: '@App\Delivery\Trip\Command\RecruitDriverHandler'
        App\Delivery\Trip\Command\MarkTripAsDeliveredCommand: '@App\Delivery\Trip\Command\MarkTripAsDeliveredHandler'