services:
  delivery.configuration.injectedList:
    class: App\Delivery\Shared\Configuration\InjectedListConfigurationManager
    public: true
    arguments:
      $configs:
        scout:
          maxDistanceValue: 500
          maxDistanceUnit: !php/enum App\Shared\Distance\Unit::Kilometer
          lastActivityUntil: '-10 minutes'

  delivery.configuration.default:
    class: App\Delivery\Shared\Configuration\DefaultValuesConfigurationManager

  delivery.configuration.withFallback:
    class: App\Delivery\Shared\Configuration\ConfigurationManagerWithFallback
    arguments:
      $mainConfigurationManager: '@delivery.configuration.injectedList'
      $fallbackConfigurationManager: '@delivery.configuration.default'

  App\Delivery\Shared\Configuration\ConfigurationManager: '@delivery.configuration.withFallback'

  delivery.configuration.manager:
    alias: App\Delivery\Shared\Configuration\ConfigurationManager