services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true

  App\Shared\Type\Location\SphericalDistanceCalculator: ~
  App\Shared\Type\Location\DistanceCalculator: '@App\Shared\Type\Location\SphericalDistanceCalculator'