services:
  delivery.driver.event.factory:
    class: App\Delivery\Driver\Event\EventFactory
    arguments:
      $uuidValidator: '@uuid.validator'

  delivery.trip.event.factory:
    class: App\Delivery\Trip\Event\EventFactory
    arguments:
      $uuidValidator: '@uuid.validator'


  App\Delivery\Trip\Event\UuidIdentifierDriverEventFactory: ~
  App\Delivery\Trip\DriverEventFactory: '@App\Delivery\Trip\Event\UuidIdentifierDriverEventFactory'

  App\Delivery\Driver\Event\Handler\UpdateTripWhenDriverReserved: ~

  App\Delivery\Driver\Event\Handler\MarkDriverAsBusyWhenTripIsMarkedAsAssigned:
    arguments:
      $driverCommandBus: '@delivery.driver.command.bus'

  App\Delivery\Trip\Event\Handler\MarkTripAsAssignedWhenDriverReserved:
    arguments:
      $tripCommandBus: '@delivery.trip.command.bus'

  App\Delivery\Driver\Event\Handler\MarkDriverAsFreeWhenTripDelivered:
    arguments:
      $tripQueryBus: '@delivery.trip.query.bus'
      $driverCommandBus: '@delivery.driver.command.bus'

  App\Delivery\Driver\Event\Handler\UnreserveDriversWhenTripIsMarkedAsAssigned:
    arguments:
      $driverCommandBus: '@delivery.driver.command.bus'

  App\Delivery\Driver\Event\Handler\ScoutDriversWhenTripCreated:
    arguments:
      $driverCommandBus: '@delivery.driver.command.bus'
      $scorer: '@delivery.scout.scorer.overall'

  delivery.event.handler.noop:
    class: App\Delivery\Shared\EventHandler\NoopEventHandler

  delivery.driver.event.dispatcher:
    class: App\Delivery\Shared\EventHandler\EventDispatcherImplementation
    public: true
    arguments:
      $handlers:
        App\Delivery\Driver\Event\Created: '@delivery.event.handler.noop'
        App\Delivery\Driver\Event\DriverReserved:
          - '@App\Delivery\Trip\Event\Handler\MarkTripAsAssignedWhenDriverReserved'

  delivery.trip.event.dispatcher:
    class: App\Delivery\Shared\EventHandler\EventDispatcherImplementation
    public: true
    arguments:
      $handlers:
        App\Delivery\Trip\Event\TripCreated:
          - '@App\Delivery\Driver\Event\Handler\ScoutDriversWhenTripCreated'
        App\Delivery\Trip\Event\TripMarkedAsInProgress:
          - '@App\Delivery\Driver\Event\Handler\MarkDriverAsBusyWhenTripIsMarkedAsAssigned'
          - '@App\Delivery\Driver\Event\Handler\UnreserveDriversWhenTripIsMarkedAsAssigned'
        App\Delivery\Trip\Event\TripDelivered:
          - '@App\Delivery\Driver\Event\Handler\MarkDriverAsFreeWhenTripDelivered'
